

FROM node:16-alpine as node16

WORKDIR /app/web

#这里需要注意以dockercompose的content为根路径
COPY . .

RUN npm config set registry https://registry.npmmirror.com

RUN npm install

RUN  npm run build


FROM nginx:alpine
COPY --from=node16 /app/web/ /app/web/
